# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LiferayCli < Formula
  desc "Tool for building and running Liferay Client Extensions"
  homepage "https://github.com/liferay/liferay-cli"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.3/liferay-darwin-arm64"
      sha256 "181cb484a24186072cabba126d0e698ff3df72abdc9f12899f9e7ecd08af4ed5"

      def install
        bin.install "liferay"
        bash_completion.install "completions/liferay.bash" => "liferay"
        zsh_completion.install "completions/liferay.zsh" => "_liferay"
        fish_completion.install "completions/liferay.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.3/liferay-darwin-amd64"
      sha256 "ea3c308df3824ebd31dd919947f8206265c1e2430a5c6cecc0621a9ec6855f7e"

      def install
        bin.install "liferay"
        bash_completion.install "completions/liferay.bash" => "liferay"
        zsh_completion.install "completions/liferay.zsh" => "_liferay"
        fish_completion.install "completions/liferay.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.3/liferay-linux-amd64"
      sha256 "1dc4632780f199e1e04f0332b536e26d6bf00127dffc3ed0c3cd8070d4dbdab0"

      def install
        bin.install "liferay"
        bash_completion.install "completions/liferay.bash" => "liferay"
        zsh_completion.install "completions/liferay.zsh" => "_liferay"
        fish_completion.install "completions/liferay.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.3/liferay-linux-arm64"
      sha256 "70ac91ba4fc9a4ee96aeffc0c5afbaef1705528937cc28db300112d6069578a7"

      def install
        bin.install "liferay"
        bash_completion.install "completions/liferay.bash" => "liferay"
        zsh_completion.install "completions/liferay.zsh" => "_liferay"
        fish_completion.install "completions/liferay.fish"
      end
    end
  end

  test do
    system "#{bin}/liferay --version"
  end
end
