# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liferay < Formula
  desc "Tool for building and running Liferay Client Extensions"
  homepage "https://github.com/liferay/liferay-cli"
  version "0.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.5/liferay-darwin-amd64"
      sha256 "49bab32f11c2b74377b53fc9da3104cba716b6e0ca46eb8b991cce72b4916da8"

      def install
        replaces = ["-amd64", "-arm64", "-darwin", "-linux"]
        Dir.glob("./*").sort.each do |entry|
          origin = File.basename(entry, File.extname(entry))
          printf "Before File: %s\n", entry
          newEntry = origin
          replaces.each do |rep|
            if newEntry.include?(rep)
              newEntry = newEntry.gsub(rep, "")
            end
          end
          printf "After File: %s\n", newEntry
          File.rename(entry, newEntry)
        end
        bin.install "liferay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.5/liferay-darwin-arm64"
      sha256 "edab95e21486308c09793e34001b50d3ea4aa5812798aadab7dc03442636026a"

      def install
        replaces = ["-amd64", "-arm64", "-darwin", "-linux"]
        Dir.glob("./*").sort.each do |entry|
          origin = File.basename(entry, File.extname(entry))
          printf "Before File: %s\n", entry
          newEntry = origin
          replaces.each do |rep|
            if newEntry.include?(rep)
              newEntry = newEntry.gsub(rep, "")
            end
          end
          printf "After File: %s\n", newEntry
          File.rename(entry, newEntry)
        end
        bin.install "liferay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.5/liferay-linux-amd64"
      sha256 "dc436cee6785fa6de16694fd4992d92811fa5c8beb6589e1d358371af9ec3dce"

      def install
        replaces = ["-amd64", "-arm64", "-darwin", "-linux"]
        Dir.glob("./*").sort.each do |entry|
          origin = File.basename(entry, File.extname(entry))
          printf "Before File: %s\n", entry
          newEntry = origin
          replaces.each do |rep|
            if newEntry.include?(rep)
              newEntry = newEntry.gsub(rep, "")
            end
          end
          printf "After File: %s\n", newEntry
          File.rename(entry, newEntry)
        end
        bin.install "liferay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.5/liferay-linux-arm64"
      sha256 "ca33d666bc8166b3e262adc40feb10f0edfb583c6225451de795fffce41e04b7"

      def install
        replaces = ["-amd64", "-arm64", "-darwin", "-linux"]
        Dir.glob("./*").sort.each do |entry|
          origin = File.basename(entry, File.extname(entry))
          printf "Before File: %s\n", entry
          newEntry = origin
          replaces.each do |rep|
            if newEntry.include?(rep)
              newEntry = newEntry.gsub(rep, "")
            end
          end
          printf "After File: %s\n", newEntry
          File.rename(entry, newEntry)
        end
        bin.install "liferay"
      end
    end
  end

  test do
    system "#{bin}/liferay --version"
  end
end
