# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liferay < Formula
  desc "Tool for building and running Liferay Client Extensions"
  homepage "https://github.com/liferay/liferay-cli"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.4/liferay-darwin-arm64"
      sha256 "d58a532ab7ac0bbea8cea56a0df541da79a69b14491a8dff0d18937a39319da0"

      def install
        inreplace "./" do |s|
          s.gsub!(/-amd64/, "")
          s.gsub!(/-arm64/, "")
          s.gsub!(/-darwin/, "")
          s.gsub!(/-linux/, "")
        end
        bin.install "liferay"
        bash_completion.install "completions/liferay.bash" => "liferay"
        zsh_completion.install "completions/liferay.zsh" => "_liferay"
        fish_completion.install "completions/liferay.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.4/liferay-darwin-amd64"
      sha256 "2b46547eac571d7469b7380dfd2ccd3c13ecbcefb5262682cd29cc350cf39b05"

      def install
        inreplace "./" do |s|
          s.gsub!(/-amd64/, "")
          s.gsub!(/-arm64/, "")
          s.gsub!(/-darwin/, "")
          s.gsub!(/-linux/, "")
        end
        bin.install "liferay"
        bash_completion.install "completions/liferay.bash" => "liferay"
        zsh_completion.install "completions/liferay.zsh" => "_liferay"
        fish_completion.install "completions/liferay.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.4/liferay-linux-arm64"
      sha256 "c81b5e6f2ddef9287b305f1d823429d9f6990fd02e715fd59cbb2e433db36a6e"

      def install
        inreplace "./" do |s|
          s.gsub!(/-amd64/, "")
          s.gsub!(/-arm64/, "")
          s.gsub!(/-darwin/, "")
          s.gsub!(/-linux/, "")
        end
        bin.install "liferay"
        bash_completion.install "completions/liferay.bash" => "liferay"
        zsh_completion.install "completions/liferay.zsh" => "_liferay"
        fish_completion.install "completions/liferay.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/liferay/liferay-cli/releases/download/v0.0.4/liferay-linux-amd64"
      sha256 "5a1744a7a051df66e2672cb511d05b2eb7d9acfba8ba1b79721341e53d89a15e"

      def install
        inreplace "./" do |s|
          s.gsub!(/-amd64/, "")
          s.gsub!(/-arm64/, "")
          s.gsub!(/-darwin/, "")
          s.gsub!(/-linux/, "")
        end
        bin.install "liferay"
        bash_completion.install "completions/liferay.bash" => "liferay"
        zsh_completion.install "completions/liferay.zsh" => "_liferay"
        fish_completion.install "completions/liferay.fish"
      end
    end
  end

  test do
    system "#{bin}/liferay --version"
  end
end
